name: Publish
on:
  push:
    tags: ["*-cn"]
    branches: ["unicode-support"]

env:
  SOLUTION_NAME: Umbra.MarePlayerMarker
  RELEASE_DIR: out/Release

jobs:
  Build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Download Dalamud Latest
        run: |
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/ottercorp/dalamud-distrib/refs/heads/main/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

      - name: Download Umbra Latest
        run: |
          Invoke-WebRequest -Uri https://github.com/ottercorp/PluginDistD17/raw/refs/heads/main/stable/Umbra/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\installedPlugins\Umbra\dist"

      - name: Restore solution
        run: dotnet restore -r win ${{ env.SOLUTION_NAME }}.sln

      - name: Build solution
        run: |
          $ver = '${{ github.ref_name }}' -replace '-cn'
          dotnet restore -r win ${{ env.SOLUTION_NAME }}.sln
          dotnet build --configuration Release --nologo -p:Version=$ver -p:FileVersion=$ver -p:AssemblyVersion=$ver

      - name: Create plugin archive
        run: Compress-Archive -Path ${{env.RELEASE_DIR}}* -DestinationPath ${{env.RELEASE_DIR}}/${{env.SOLUTION_NAME}}.zip

      - name: Publish Plugin
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{env.RELEASE_DIR}}/${{env.SOLUTION_NAME}}.zip
